name: DevSecOps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: azure
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: check docker version
      run: |
           docker --version
           
    - name: check git version
      run: |
           git --version       
