name: DevSecOps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: azure
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: check Kubernetes version
      run: |
        sudo echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config
        sudo kubectl version

    - name: check docker version
      run: |
        sudo docker version
